import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { FC, PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Teste técnico',
  description: 'Generated by create next app',
  viewport:
    'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="pt" className={inter.className}>
      <body className="flex max-md:flex-col">{children}</body>
    </html>
  );
};
export default RootLayout;
